#!/usr/bin/env python3
"""Generate and validate the tagged table of contents over docs/knowledge/notes/.

Each note carries a `bookmarks:` frontmatter key. Two states are distinct and
both valid:

- missing the `bookmarks:` key entirely  -> note has not been reviewed yet.
- `bookmarks: []` (explicit empty list)   -> reviewed, deliberately nothing noteworthy.

`BOOKMARKS.md` is a hand-authored allow-list (a markdown table, one row per
bookmark) — this script only *reads* it to validate against, it never writes
to it. `INDEX.md` is the one generated artifact; regenerate it with no
arguments after editing any note's frontmatter.

Usage:
    python3 scripts/notes/index.py                 # regenerate INDEX.md
    python3 scripts/notes/index.py --check          # exit non-zero if stale/invalid (for CI)
"""

import re
import sys
from pathlib import Path
from typing import Dict, List, Set, Tuple

NOTES_DIR = Path("docs/knowledge/notes")
BOOKMARKS_FILE = NOTES_DIR / "BOOKMARKS.md"
INDEX_FILE = NOTES_DIR / "INDEX.md"
EXCLUDED_FILES = {"TEMPLATE.md", "BOOKMARKS.md", "INDEX.md"}

FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)
BOOKMARKS_KEY_RE = re.compile(r"^bookmarks:\s*\[(.*)\]\s*$", re.MULTILINE)
VOCAB_ROW_RE = re.compile(r"^\|\s*`?([a-z0-9-]+)`?\s*\|")

GENERATED_BANNER = "<!-- Generated by scripts/notes/index.py — do not edit by hand -->"


def iter_notes(notes_dir: Path) -> List[Path]:
    """All note files in scan order, excluding the template and generated files."""
    return sorted(p for p in notes_dir.glob("*.md") if p.name not in EXCLUDED_FILES)


def parse_note(path: Path) -> Tuple[bool, List[str]]:
    """Return (has_bookmarks_key, bookmarks). has_bookmarks_key is False when
    the file has no frontmatter block, or the block has no `bookmarks:` key."""
    text = path.read_text(encoding="utf-8")
    match = FRONTMATTER_RE.match(text)
    if not match:
        return False, []
    key_match = BOOKMARKS_KEY_RE.search(match.group(1))
    if not key_match:
        return False, []
    raw = key_match.group(1).strip()
    if not raw:
        return True, []
    items = [item.strip().strip("'\"") for item in raw.split(",")]
    return True, [item for item in items if item]


def load_vocabulary(vocab_file: Path) -> Set[str]:
    """Parse the hand-authored bookmark allow-list from its markdown table."""
    if not vocab_file.exists():
        return set()
    vocab = set()
    for line in vocab_file.read_text(encoding="utf-8").splitlines():
        match = VOCAB_ROW_RE.match(line)
        if match and set(match.group(1)) != {"-"} and match.group(1) != "Bookmark":
            vocab.add(match.group(1))
    return vocab


def render_index(notes_dir: Path, vocab_file: Path) -> str:
    """Deterministically render INDEX.md content from the current corpus."""
    vocabulary = load_vocabulary(vocab_file)
    by_bookmark: Dict[str, List[Tuple[str, str]]] = {b: [] for b in sorted(vocabulary)}
    untagged: List[Tuple[str, str]] = []

    for note in iter_notes(notes_dir):
        text = note.read_text(encoding="utf-8")
        title_match = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
        title = title_match.group(1).strip() if title_match else note.stem
        has_key, bookmarks = parse_note(note)
        if not has_key or not bookmarks:
            untagged.append((note.name, title))
            continue
        for bookmark in bookmarks:
            by_bookmark.setdefault(bookmark, []).append((note.name, title))

    lines = [GENERATED_BANNER, "", "# Notes index", "",
             "Generated from `bookmarks:` frontmatter in `docs/knowledge/notes/*.md`. "
             "Run `python3 scripts/notes/index.py` after tagging changes.", ""]

    lines.append("## Top themes")
    lines.append("")
    ranked = sorted(((b, notes) for b, notes in by_bookmark.items() if notes),
                     key=lambda pair: (-len(pair[1]), pair[0]))
    for bookmark, notes in ranked:
        lines.append(f"- **{bookmark}** ({len(notes)})")
    lines.append("")

    lines.append("## By bookmark")
    lines.append("")
    for bookmark in sorted(by_bookmark):
        notes = by_bookmark[bookmark]
        if not notes:
            continue
        lines.append(f"### {bookmark}")
        for filename, title in sorted(notes):
            lines.append(f"- [{title}]({filename})")
        lines.append("")

    if untagged:
        lines.append("## No bookmarks yet")
        lines.append("")
        for filename, title in sorted(untagged):
            lines.append(f"- [{title}]({filename})")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def write_index(notes_dir: Path, vocab_file: Path, index_file: Path) -> None:
    index_file.write_text(render_index(notes_dir, vocab_file), encoding="utf-8")


def check(notes_dir: Path, vocab_file: Path, index_file: Path) -> List[str]:
    """Return a list of validation errors (empty list = clean)."""
    errors = []
    vocabulary = load_vocabulary(vocab_file)

    for note in iter_notes(notes_dir):
        has_key, bookmarks = parse_note(note)
        if not has_key:
            errors.append(
                f"{note.name}: missing 'bookmarks:' key "
                f"(use bookmarks: [] if genuinely nothing noteworthy applies)"
            )
            continue
        for bookmark in bookmarks:
            if bookmark not in vocabulary:
                errors.append(f"{note.name}: unknown bookmark '{bookmark}' — add it to BOOKMARKS.md first")

    expected = render_index(notes_dir, vocab_file)
    actual = index_file.read_text(encoding="utf-8") if index_file.exists() else None
    if actual != expected:
        errors.append("INDEX.md is stale — run `python3 scripts/notes/index.py` to regenerate")

    return errors


def apply_bookmarks(notes_dir: Path, mapping: Dict[str, List[str]]) -> None:
    """One-shot backfill: insert a `bookmarks:` frontmatter block into each
    named file, in place. Never touches a file that already has the key."""
    for filename, bookmarks in mapping.items():
        path = notes_dir / filename
        text = path.read_text(encoding="utf-8")
        has_key, _ = parse_note(path)
        if has_key:
            continue
        body = text
        if FRONTMATTER_RE.match(text):
            # Frontmatter exists but without a bookmarks key — insert the key into it.
            frontmatter_match = FRONTMATTER_RE.match(text)
            new_frontmatter = frontmatter_match.group(1) + f"\nbookmarks: [{', '.join(bookmarks)}]"
            body = f"---\n{new_frontmatter}\n---\n" + text[frontmatter_match.end():]
        else:
            body = f"---\nbookmarks: [{', '.join(bookmarks)}]\n---\n\n" + text
        path.write_text(body, encoding="utf-8")


def main(argv: List[str]) -> int:
    mode = argv[0] if argv else None

    if mode in (None,):
        write_index(NOTES_DIR, BOOKMARKS_FILE, INDEX_FILE)
        print(f"Regenerated {INDEX_FILE}")
        return 0

    if mode == "--check":
        errors = check(NOTES_DIR, BOOKMARKS_FILE, INDEX_FILE)
        if errors:
            for error in errors:
                print(f"ERROR: {error}", file=sys.stderr)
            return 1
        print("OK")
        return 0

    print(f"Unknown mode: {mode}", file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
